version: "3"

services:
  db:
    image: postgres:12
    env_file: .env

  web:
    build:
      context: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
