# Generated by Django 3.1 on 2022-02-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carne', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comidass',
            },
        ),
    ]
